myName = input('What is your name?: ')
myFood = input('What is your favorite food?: ')
myMusic = input('What is your favorite music?: ')
myCity = input('Where do you live?: ')
print('You are: ')
print(myName)
print('You are probably hungry for')
print(myFood)
print('and you are definitely getting your groove on to')
print(myMusic)
print('living in the amazing')
print(myCity)
